// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6HTwi_8Lyixn_HvFnUquzZy5oS0rLqwk',
    appId: '1:973996384416:web:70336c664d112e9acce9c5',
    messagingSenderId: '973996384416',
    projectId: 'billmanagement-99681',
    authDomain: 'billmanagement-99681.firebaseapp.com',
    storageBucket: 'billmanagement-99681.appspot.com',
    measurementId: 'G-EGDF47TB8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgbf4lWINmSKxEPGbQk5iskTV2UW5-I2Q',
    appId: '1:973996384416:android:d34f9ffaf01c149ecce9c5',
    messagingSenderId: '973996384416',
    projectId: 'billmanagement-99681',
    storageBucket: 'billmanagement-99681.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqBDvrevyUi-O8PNGZFJNXN69DwlF6gaU',
    appId: '1:973996384416:ios:1292471c3baad8f5cce9c5',
    messagingSenderId: '973996384416',
    projectId: 'billmanagement-99681',
    storageBucket: 'billmanagement-99681.appspot.com',
    iosBundleId: 'com.example.webPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqBDvrevyUi-O8PNGZFJNXN69DwlF6gaU',
    appId: '1:973996384416:ios:261b2c47a26622fccce9c5',
    messagingSenderId: '973996384416',
    projectId: 'billmanagement-99681',
    storageBucket: 'billmanagement-99681.appspot.com',
    iosBundleId: 'com.example.webPortal.RunnerTests',
  );
}
